runtime: nodejs16
env: standard
instance_class: F1
handlers:
- url: /api/.*
  secure: always
  redirect_http_response_code: 301
  script: auto
- url: /
  static_files: www/index.html
  upload: www/index.html
  expiration: "2s"
- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  expiration: "1s"